class Frames(object):

    ASSOCIATION_REQUEST = "0x00"
    ASSOCIATION_RESPONSE = "0x01"
    REASSOCIATION_REQUEST = "0x02"
    REASSOCIATION_RESPONSE = "0x03"
    PROBE_REQUEST = "0x04"
    PROBE_RESPONSE = "0x05"
    BEACON = "0x08"
    DATA = "0x20"
    QOS_DATA = "0x28"
