// Code generated by protoc-gen-go.
// source: wifi.proto
// DO NOT EDIT!

/*
Package wifiproto is a generated protocol buffer package.

It is generated from these files:
	wifi.proto

It has these top-level messages:
	Packet
	Payload
*/
package wifiproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Packet struct {
	Arrival          *float64 `protobuf:"fixed64,1,opt,name=arrival" json:"arrival,omitempty"`
	Subtype          *string  `protobuf:"bytes,2,opt,name=subtype" json:"subtype,omitempty"`
	Ssid             *string  `protobuf:"bytes,3,opt,name=ssid" json:"ssid,omitempty"`
	Source           *string  `protobuf:"bytes,4,opt,name=source" json:"source,omitempty"`
	Destination      *string  `protobuf:"bytes,5,opt,name=destination" json:"destination,omitempty"`
	Freq             *int32   `protobuf:"varint,6,opt,name=freq" json:"freq,omitempty"`
	Signal           *int32   `protobuf:"varint,7,opt,name=signal" json:"signal,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Packet) Reset()                    { *m = Packet{} }
func (m *Packet) String() string            { return proto.CompactTextString(m) }
func (*Packet) ProtoMessage()               {}
func (*Packet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Packet) GetArrival() float64 {
	if m != nil && m.Arrival != nil {
		return *m.Arrival
	}
	return 0
}

func (m *Packet) GetSubtype() string {
	if m != nil && m.Subtype != nil {
		return *m.Subtype
	}
	return ""
}

func (m *Packet) GetSsid() string {
	if m != nil && m.Ssid != nil {
		return *m.Ssid
	}
	return ""
}

func (m *Packet) GetSource() string {
	if m != nil && m.Source != nil {
		return *m.Source
	}
	return ""
}

func (m *Packet) GetDestination() string {
	if m != nil && m.Destination != nil {
		return *m.Destination
	}
	return ""
}

func (m *Packet) GetFreq() int32 {
	if m != nil && m.Freq != nil {
		return *m.Freq
	}
	return 0
}

func (m *Packet) GetSignal() int32 {
	if m != nil && m.Signal != nil {
		return *m.Signal
	}
	return 0
}

type Payload struct {
	Location         *string   `protobuf:"bytes,1,opt,name=location" json:"location,omitempty"`
	Sensor           *string   `protobuf:"bytes,2,opt,name=sensor" json:"sensor,omitempty"`
	Data             []*Packet `protobuf:"bytes,3,rep,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *Payload) Reset()                    { *m = Payload{} }
func (m *Payload) String() string            { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()               {}
func (*Payload) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Payload) GetLocation() string {
	if m != nil && m.Location != nil {
		return *m.Location
	}
	return ""
}

func (m *Payload) GetSensor() string {
	if m != nil && m.Sensor != nil {
		return *m.Sensor
	}
	return ""
}

func (m *Payload) GetData() []*Packet {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Packet)(nil), "wifiproto.Packet")
	proto.RegisterType((*Payload)(nil), "wifiproto.Payload")
}

var fileDescriptor0 = []byte{
	// 188 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x3c, 0x8f, 0xcd, 0x8e, 0x82, 0x30,
	0x14, 0x85, 0xd3, 0xe1, 0x6f, 0xb8, 0x4c, 0x46, 0xad, 0x9b, 0xee, 0x34, 0xac, 0x58, 0xb1, 0xf0,
	0x39, 0x5c, 0xf0, 0x0a, 0x57, 0x5a, 0x4c, 0x23, 0x69, 0xb1, 0x2d, 0x1a, 0xe2, 0xcb, 0x5b, 0x8a,
	0xb2, 0xbb, 0xdf, 0x49, 0xce, 0xfd, 0x72, 0x00, 0x9e, 0xb2, 0x93, 0xf5, 0x60, 0xb4, 0xd3, 0x34,
	0x9f, 0xef, 0x70, 0x96, 0x2f, 0x48, 0x1b, 0x6c, 0x6f, 0xc2, 0xd1, 0x0d, 0x64, 0x68, 0x8c, 0x7c,
	0x60, 0xcf, 0xc8, 0x91, 0x54, 0x64, 0x0e, 0xec, 0x78, 0x71, 0xd3, 0x20, 0xd8, 0x8f, 0x0f, 0x72,
	0xfa, 0x07, 0xb1, 0xb5, 0x92, 0xb3, 0x28, 0xd0, 0x3f, 0xa4, 0x56, 0x8f, 0xa6, 0x15, 0x2c, 0x0e,
	0xbc, 0x87, 0x82, 0x0b, 0xeb, 0xa4, 0x42, 0x27, 0xb5, 0x62, 0xc9, 0xb7, 0xd2, 0x19, 0x71, 0x67,
	0xa9, 0xa7, 0x24, 0x54, 0xe4, 0x55, 0x79, 0x43, 0x36, 0x73, 0x79, 0x86, 0xac, 0xc1, 0xa9, 0xd7,
	0xc8, 0xe9, 0x16, 0x7e, 0x7b, 0xdd, 0x2e, 0x55, 0xb2, 0xfe, 0x17, 0xca, 0x6a, 0xf3, 0xb1, 0x1f,
	0x20, 0xe6, 0xe8, 0xd0, 0xdb, 0xa3, 0xaa, 0x38, 0xed, 0xea, 0x75, 0x43, 0xbd, 0x0c, 0x78, 0x07,
	0x00, 0x00, 0xff, 0xff, 0x4b, 0x06, 0x94, 0x98, 0xe2, 0x00, 0x00, 0x00,
}
